//! Cross-language artifact generator for folio.
//!
//! Reads the character constants declared in `src/token.zig` via comptime
//! reflection and emits the mirrors the tree-sitter-folio build vendors as
//! source files:
//!
//!   generated/constants.js   sigil characters for the grammar JS
//!   generated/constants.h    same, as #defines for the external C scanner
//!
//! tree-sitter-folio's JS + C build can't read a Zig file, so it consumes these
//! generated copies (see tree-sitter-folio/scripts/sync.js) instead of
//! hand-mirroring folio's character constants. Run with `zig build gen`; the
//! output directory is the first argument.
//!
//! This mirrors lish/tools/gen.zig. folio declares only printable structural
//! characters (no parse-time limits, no escape table), so only the character
//! constants are emitted; the scanner hardcodes the universal `\n`/`\r`.
//!
//! Reflection collects each integer-valued `pub const` of `token.zig` in the
//! printable range 0x20..0x7E; control chars (`\n`, `\r`) and the `//` comment
//! string are skipped.

const std = @import("std");
const folio = @import("folio");
const token = folio.token;

const CHAR_MIN = 0x20;
const CHAR_MAX = 0x7E;

const HEADER =
    \\// Generated by folio/tools/gen.zig from src/token.zig.
    \\// DO NOT EDIT. Run `zig build gen` to regenerate.
    \\
;

const Constant = struct {
    name: []const u8,
    value: i128,
};

/// Every integer `pub const` of `token.zig` whose value is a printable
/// character, in source-declaration order.
fn collectCharacters() []const Constant {
    comptime {
        var out: []const Constant = &.{};
        for (@typeInfo(token).@"struct".decls) |decl| {
            const value = @field(token, decl.name);
            switch (@typeInfo(@TypeOf(value))) {
                .int, .comptime_int => {
                    const wide: i128 = value;
                    if (wide >= CHAR_MIN and wide <= CHAR_MAX) {
                        out = out ++ &[_]Constant{.{ .name = decl.name, .value = wide }};
                    }
                },
                else => {},
            }
        }
        return out;
    }
}

const characters = collectCharacters();

fn longestName() comptime_int {
    comptime {
        var max = 0;
        for (characters) |c| {
            if (c.name.len > max) max = c.name.len;
        }
        return max;
    }
}

fn padding(comptime name: []const u8, comptime width: comptime_int) []const u8 {
    return " " ** (width - name.len + 1);
}

fn jsValue(comptime value: i128) []const u8 {
    return switch (@as(u8, @intCast(value))) {
        '\'' => "\"'\"",
        '\\' => "'\\\\'",
        else => |ch| std.fmt.comptimePrint("'{c}'", .{ch}),
    };
}

fn cValue(comptime value: i128) []const u8 {
    return switch (@as(u8, @intCast(value))) {
        '\'' => "'\\''",
        '\\' => "'\\\\'",
        else => |ch| std.fmt.comptimePrint("'{c}'", .{ch}),
    };
}

fn buildJs() []const u8 {
    comptime {
        const width = longestName();
        var out: []const u8 = HEADER ++ "\nmodule.exports = {\n    // Structural source characters.\n";
        for (characters) |c| {
            out = out ++ "    " ++ c.name ++ ":" ++ padding(c.name, width) ++ jsValue(c.value) ++ ",\n";
        }
        return out ++ "};\n";
    }
}

fn buildC() []const u8 {
    comptime {
        const prefix = "FOLIO_";
        const width = longestName() + prefix.len;
        var out: []const u8 = HEADER ++
            \\
            \\#ifndef FOLIO_TREE_SITTER_CONSTANTS_H
            \\#define FOLIO_TREE_SITTER_CONSTANTS_H
            \\
            \\// Structural source characters.
            \\
        ;
        for (characters) |c| {
            const name = prefix ++ c.name;
            out = out ++ "#define " ++ name ++ padding(name, width) ++ cValue(c.value) ++ "\n";
        }
        return out ++ "\n#endif\n";
    }
}

const js_content = buildJs();
const c_content = buildC();

pub fn main(init: std.process.Init) !void {
    const io = init.io;

    var stderr_writer = std.Io.File.stderr().writer(io, &.{});
    const stderr = &stderr_writer.interface;

    var arg_iter = init.minimal.args.iterate();
    _ = arg_iter.next(); // skip argv[0]
    const out_dir = arg_iter.next() orelse {
        try stderr.writeAll("usage: gen <output-directory>\n");
        return error.MissingOutputDirectory;
    };

    const cwd = std.Io.Dir.cwd();
    try cwd.createDirPath(io, out_dir);

    try writeInto(io, cwd, out_dir, "constants.js", js_content);
    try writeInto(io, cwd, out_dir, "constants.h", c_content);

    var stdout_writer = std.Io.File.stdout().writer(io, &.{});
    const stdout = &stdout_writer.interface;
    try stdout.print("gen: wrote constants.js, constants.h to {s}\n", .{out_dir});
}

fn writeInto(io: std.Io, dir: std.Io.Dir, out_dir: []const u8, name: []const u8, data: []const u8) !void {
    var path_buf: [std.fs.max_path_bytes]u8 = undefined;
    const path = try std.fmt.bufPrint(&path_buf, "{s}/{s}", .{ out_dir, name });
    try dir.writeFile(io, .{ .sub_path = path, .data = data });
}
